import Head from 'next/head'
import { Inter } from 'next/font/google'
import {
  Heading,
  Flex,
  Text,
  Center,
  Button,
  VStack,
  Box
} from '@chakra-ui/react'
import Layout from '@/components/layout/Layout'
import InputArea from '@/components/InputArea'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [value, setValue] = useState('')

  const handleInputChange = () => {
    setValue(value)
  }
  return (
    <>
      <Head>
        <title>Redirector</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {' '}
        <main className={`${inter.className}`}>
          <Center>
            <Heading>Redirector</Heading>
          </Center>
          <Text textAlign='center'>Lorem Ipsum Dolor sit Amet</Text>
          <Flex
            gap={6}
            direction={['column', 'column', 'row']}
            p={8}
            justifyContent='space-between'
          >
            <VStack w='100%' h='100%'>
              {' '}
              <InputArea
                placeholder='jweb URLs go here'
                bgColor='transparent'
              />
              <Button colorScheme='teal' mt={2}>
                Clear Text Areas
              </Button>
            </VStack>
            <VStack w='100%'>
              <InputArea placeholder='elevate URLs go here' value={value} />
              <Button colorScheme='red' mt={2} onClick={handleInputChange}>
                Generate Redirects
              </Button>
            </VStack>
            <Box
              bg='transparent'
              w='100%'
              borderRadius='lg'
              borderColor='gray.200'
              borderWidth={1}
              p={2}
            >
              {value}
            </Box>
          </Flex>
        </main>
      </Layout>
    </>
  )
}
